name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: devlopment 
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # Pinned to specific version
          terraform_wrapper: false 

      - name: Terraform Init
        working-directory: infrastructure/environments/dev
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infrastructure/environments/dev
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: infrastructure/environments/dev
        run: terraform apply -input=false -auto-approve
